"""Add workflow models

Revision ID: b6c0fb6cfebc
Revises: 0001
Create Date: 2026-05-11 15:58:37.026783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'b6c0fb6cfebc'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('action_by_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_history_id'), 'approval_history', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('tasks', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('todo', 'in_progress', 'review', 'done', name='statusenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'"))
    op.alter_column('tasks', 'priority',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('low', 'medium', 'high', name='priorityenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'users', ['updated_by_id'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', name='priorityenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('todo', 'in_progress', 'review', 'done', name='statusenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'todo'"))
    op.drop_column('tasks', 'updated_by_id')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_approval_history_id'), table_name='approval_history')
    op.drop_table('approval_history')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
